carshop/urls.py
from django.urls import path

from . import views

app_name = "carshop"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:id>/", views.detail, name="detail"),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    path("carshop/", include("carshop.urls")),
    path("admin/", admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

carshop/models.py
from django.db import models

# Create your models here.

class Car(models.Model):
    car_manufacturer = models.CharField(max_length=200)
    car_model = models.CharField(max_length=200)
    car_price =  models.IntegerField()
    car_build_year =  models.IntegerField()
    car_description =  models.TextField(null=True, blank=True)
    pub_date = models.DateTimeField("date published")
    image_one = models.ImageField(upload_to='images', blank=True)
    car_mileage =  models.IntegerField(null=True)
    transmission_type = models.CharField(max_length=200, null=True)
    fuel_type = models.CharField(max_length=200, null=True)



    def __str__(self):
        return self.car_manufacturer + " " + self.car_model + " " + str(self.car_build_year)

carshop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Car
from django.template import loader

# Create your views here.

# this is the longer way of doing things
# def index(request):
#     most_recent_list = Car.objects.order_by("-pub_date")[:5]
#     template = loader.get_template("carshop/index.html")
#     context = {
#         "most_recent_list": most_recent_list,
#     }
#     return HttpResponse(template.render(context, request))

# the below is a shortcut
def index(request):
    most_recent_list = Car.objects.order_by("-pub_date")[:5]
    context = {"most_recent_list": most_recent_list}
    return render(request, "carshop/index.html", context)

# def detail(request, id):
#     return HttpResponse("You're looking at question %s." % id)

# def detail(request, id):
#     try:
#         car = Car.objects.get(pk=id)
#     except Car.DoesNotExist:
#         raise Http404("entry does not exist")
#     return render(request, "carshop/detail.html", {"car": car})

# shortcut, above are longer
def detail(request, id):
    car = get_object_or_404(Car, pk=id)
    return render(request, "carshop/detail.html", {"car": car})

carshop/templates/carshop/detail.html
{% load static %} {% load humanize %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'carshop/style.css' %}" />
    {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
  </head>
  <body>
    <!-- navbar  -->

    <header>
      <nav class="navbar navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'carshop:index' %}">
            Cheshire Car Shop
          </a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="offcanvas"
            data-bs-target="#offcanvasDarkNavbar"
            aria-controls="offcanvasDarkNavbar"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div
            class="offcanvas offcanvas-end text-bg-dark"
            tabindex="-1"
            id="offcanvasDarkNavbar"
            aria-labelledby="offcanvasDarkNavbarLabel"
          >
            <div class="offcanvas-header bg-dark">
              <h5
                class="offcanvas-title text-light"
                id="offcanvasDarkNavbarLabel"
              >
                Menu
              </h5>
              <button
                type="button"
                class="btn-close btn-close-white"
                data-bs-dismiss="offcanvas"
                aria-label="Close"
              ></button>
            </div>
            <div class="offcanvas-body bg-dark">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#"
                    >Home</a
                  >
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Cars</a>
                </li>
                <li class="nav-item dropdown">
                  <a
                    class="nav-link dropdown-toggle"
                    href="#"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    Additional Information
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark">
                    <li><a class="dropdown-item" href="#">Contact</a></li>
                    <li>
                      <a class="dropdown-item" href="#">Finance</a>
                    </li>
                    <li>
                      <hr class="dropdown-divider" />
                    </li>
                    <li>
                      <a class="dropdown-item" href="#">Special offers</a>
                    </li>
                  </ul>
                </li>
              </ul>
              <!-- <form class="d-flex mt-3" role="search">
                <input
                  class="form-control me-2"
                  type="search"
                  placeholder="Search"
                  aria-label="Search"
                />
                <button class="btn btn-success" type="submit">Search</button>
              </form> -->
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <div class="container" id="detailContainer">
        <div class="row">
          <div class="col-12 col-lg-6 my-auto">
            {% if car.image_one %}
            <img src="{{ car.image_one.url}}" class="img-fluid" alt="" />
            {% endif %}
          </div>
          <div class="col my-3">
            <div id="blueInfoBox">
              <p>
                <img
                  src="{% static 'carshop\images\checked.png' %}  "
                  alt=""
                />2 years' unlimited mileage warranty
              </p>
              <p>
                <img
                  src="{% static 'carshop\images\checked.png' %}  "
                  alt=""
                />2 years roadside assistance
              </p>
              <p>
                <img
                  src="{% static 'carshop\images\checked.png' %}  "
                  alt=""
                />2 years' MOT cover
              </p>
              <p>
                <img
                  src="{% static 'carshop\images\checked.png' %}  "
                  alt=""
                />Flexible finance available
              </p>
            </div>

            <div class="text-center mt-4">
              <h2 class="fs-1">
                {{car.car_build_year}} {{car.car_manufacturer}}
                {{car.car_model}}
              </h2>
              <p class="mb-1">our price</p>
              <p class="fw-bold">£{{car.car_price|intcomma}}</p>
              <p>{{car.car_description}}</p>
            </div>

            <div class="card-body bg-dark d-inline-flex px-auto py-0 w-100 mb-3 rounded">
              <li
                class="list-group-item border-0 bg-dark text-light px-0 mx-auto"
              >
                <img
                  src="{% static 'carshop\images\speedometer-32.png' %}  "
                  alt=""
                  class="cardFooterImg"
                />
                {{ car.car_mileage|intcomma }}
              </li>
              <li
                class="list-group-item bg-dark border-0 text-light px-0 mx-auto"
              >
                <img
                  src="{% static 'carshop\images\car-4-32.png' %}  "
                  alt=""
                  class="cardFooterImg"
                />
                {{ car.transmission_type }}
              </li>
              <li
                class="list-group-item bg-dark border-0 text-light px-0 mx-auto"
              >
                <img
                  src="{% static 'carshop\images\gas-pump-24.png' %}  "
                  alt=""
                  class="cardFooterImg"
                />
                {{ car.fuel_type }}
              </li>
            </div>

            <div class="text-center">
              <a class="btn btn-primary border-0" href="#" role="button"
                >Reserve now</a
              >
              <a class="btn btn-primary border-0" href="#" role="button"
                >Test drive</a
              >
              <a class="btn btn-primary border-0" href="#" role="button"
                >Make enquiry</a
              >
            </div>
          </div>
        </div>
        <div class="row mb-5">
          <a href="{% url 'carshop:index' %}">Return to home page</a>
        </div>
      </div>
    </main>
  </body>
</html>

carshop/templates/carshop/index.html
{% load static %} {% load humanize %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'carshop/style.css' %}" />
    {% load bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
  </head>

  <body>
    <!-- navbar  -->

    <header>
      <nav class="navbar navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'carshop:index' %}">
            Cheshire Car Shop
          </a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="offcanvas"
            data-bs-target="#offcanvasDarkNavbar"
            aria-controls="offcanvasDarkNavbar"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div
            class="offcanvas offcanvas-end text-bg-dark"
            tabindex="-1"
            id="offcanvasDarkNavbar"
            aria-labelledby="offcanvasDarkNavbarLabel"
          >
            <div class="offcanvas-header bg-dark">
              <h5
                class="offcanvas-title text-light"
                id="offcanvasDarkNavbarLabel"
              >
                Menu
              </h5>
              <button
                type="button"
                class="btn-close btn-close-white"
                data-bs-dismiss="offcanvas"
                aria-label="Close"
              ></button>
            </div>
            <div class="offcanvas-body bg-dark">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#"
                    >Home</a
                  >
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Cars</a>
                </li>
                <li class="nav-item dropdown">
                  <a
                    class="nav-link dropdown-toggle"
                    href="#"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    Additional Information
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark">
                    <li><a class="dropdown-item" href="#">Contact</a></li>
                    <li>
                      <a class="dropdown-item" href="#">Finance</a>
                    </li>
                    <li>
                      <hr class="dropdown-divider" />
                    </li>
                    <li>
                      <a class="dropdown-item" href="#">Special offers</a>
                    </li>
                  </ul>
                </li>
              </ul>
              <!-- <form class="d-flex mt-3" role="search">
                <input
                  class="form-control me-2"
                  type="search"
                  placeholder="Search"
                  aria-label="Search"
                />
                <button class="btn btn-success" type="submit">Search</button>
              </form> -->
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <!-- {% if most_recent_list %}
      <ul>
        {% for car in most_recent_list %}
        <li>
          <a href="{% url 'carshop:detail' car.id %}"
            >{{ car.car_manufacturer }} - {{car.car_model}}</a
          >
        </li>
        {% endfor %}
      </ul>
      {% else %}
      <p>No cars are available.</p>
      {% endif %} -->

      <!-- main banner  -->

      <div id="mainBanner">
        <div id="mainBannerBox">
          <h2>Approved Used Volkswagens</h2>
          <p>at Cheshire Car Shop</p>
          <ul>
            <li>
              <img src="{% static 'carshop\images\checked.png' %}  " alt="" />
              24 months' Warranty
            </li>
            <li>
              <img src="{% static 'carshop\images\checked.png' %}  " alt="" />
              24 months' Roadside Assistance
            </li>
            <li>
              <img src="{% static 'carshop\images\checked.png' %}  " alt="" />
              24 months' MOT Cover
            </li>
          </ul>
          <p>...all included in the price of the car!</p>
        </div>
      </div>

      <!-- car cards  -->

      <div class="container-fluid py-5">
        <h2 class="py-5 ms-5">Latest Stock</h2>
        <div class="row container-fluid mx-auto">
          {% if most_recent_list %} {% for car in most_recent_list %}
          <div class="col-12 col-md-6 col-lg-4">
            <a href="{% url 'carshop:detail' car.id %}" id="cardLink">
              <div class="card mx-auto mb-5 w-100">
                {% if car.image_one %}
                <img
                  src="{{ car.image_one.url}}"
                  class="card-img-top cardCarImg"
                  alt="..."
                />
                {% endif %}
                <div class="card-body pb-0">
                  <h5 class="card-title text-center">
                    {{ car.car_build_year }} {{ car.car_manufacturer }}
                    {{car.car_model }}
                  </h5>
                  <!-- <p class="card-text">
                  Some quick example text to build on the card title and make up
                  the bulk of the card's content.
                </p> -->
                </div>
                <ul class="list-group list-group-flush border-0 p-0">
                  <li class="list-group-item border-0 text-center p-0 m-0">
                    Our Price
                  </li>
                  <li
                    class="list-group-item border-0 text-center pt-0 pb-4 fw-bold"
                  >
                    £{{ car.car_price|intcomma}}
                  </li>
                </ul>
                <div class="card-body bg-dark d-inline-flex px-auto py-3">
                  <li
                    class="list-group-item border-0 bg-dark text-light px-0 mx-auto"
                  >
                    <img
                      src="{% static 'carshop\images\speedometer-32.png' %}  "
                      alt=""
                      class="cardFooterImg"
                    />
                    {{ car.car_mileage|intcomma }}
                  </li>
                  <li
                    class="list-group-item bg-dark border-0 text-light px-0 mx-auto"
                  >
                    <img
                      src="{% static 'carshop\images\car-4-32.png' %}  "
                      alt=""
                      class="cardFooterImg"
                    />
                    {{ car.transmission_type }}
                  </li>
                  <li
                    class="list-group-item bg-dark border-0 text-light px-0 mx-auto"
                  >
                    <img
                      src="{% static 'carshop\images\gas-pump-24.png' %}  "
                      alt=""
                      class="cardFooterImg"
                    />
                    {{ car.fuel_type }}
                  </li>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}{% endif %}
        </div>
      </div>
    </main>
  </body>
</html>